### ISSUE TITLE
FLIF image significantly larger than some low bitdepth greyscale pngs

### ISSUE THREAD

**Issue by ilwaz** [FLIF-hub/FLIF#139]
FLIF works great on some greyscale images, but seems to choke on lower bitdepth ones. The following image is a 403KB png which encodes to a 798KB flif. If you take out the restriction on greyscale images in the PLT transform, the flif size is reduced to 552KB, but I'm not sure if this effects other greyscale images for the worse. 

This example is extreme, but with other low bitdepth images I'm getting ~70% PNG file size with PLT vs ~101% PNG files size without (so larger than source files).

Is it possible to force PLT for greyscale images with a flag, or have a better way of picking whether to use PLT or ACB for these kinds of images?

![hard_4](https://cloud.githubusercontent.com/assets/15661146/10954064/4ee4eae0-8319-11e5-9510-2712e64ae87f.png)

**Comment by jonsneyers** [comment]
Interesting. The reason I disabled PLT for grayscale images was that it's redundant if it's 8-bit grayscale  and for 1-bit black & white images it seemed to give worse performance. But this was not really tested extensively. So I think it makes sense to enable PLT for grayscale, and you can use `-p0` to disable it.

**Comment by ilwaz** [comment]
After running some more tests, PLT on greyscale images with 4,5,6,8-bit colors ranges stored in 8,16,24,32-bit png formats resulted in smaller file sizes (60-99% filesize) a bit more than 50% of the time. The remainder resulted in files 100-100.07% filesize without PLT. Performance is anywhere from 60-130% of that without PLT though. Also these tests weren't extensive. I'm working with largish files (1400x2000 greyscale pngs) of a specific style (manga scans, so white spaces, some text, lines, and some halftone patterns).

**Comment by jonsneyers** [comment]
From my (very limited) testing, it looks like PLT is a good idea on grayscale, but not a good idea on 1-bit black & white images. For some reason (probably related to rounding in the pixel estimation and/or MANIAC tree learning), it is better to work with pixels that are 0 or 255 instead of pixels that are 0 or 1. This needs some further investigation.

Enabling PLT on single-channel images is a bit tricky because that code is hardcoded for (at least) 3 channels. Of course bogus constant/duplicate planes could be added or the code could be modified to deal with 1 channel. At the moment, FLIF does not auto-detect RGB images being effectively grayscale, so it will be have differently on grayscale input encoded as an RGB png or ppm (P6) than on grayscale input encoded as grayscale png or pbm/pgm (P4 or P5).

For now, I'll just enable PLT on RGB inputs that are effectively grayscale. So if you give it a pbm or pgm file, it will not use PLT (and in the case of pbm that's probably a good thing), but if you give it a ppm which is effectively grayscale, then it will use PLT by default.

Halftone patterns (and typeset text) probably compress better with something LZ-based like PNG, because of the repetitive nature of such patterns. Also if you don't need progressive decoding, `flif -n` tends to be smaller for non-photographic material.

**Comment by jonsneyers** [comment]
Commit https://github.com/FLIF-hub/FLIF/commit/6f342cebd5cb96043aee31c0c78f9c9514ae888f improves the situation.

It's still not fully satisfactory though: on this specific image, FLIF is still worse than PNG, it's even worse than a `gzip`'ed PGM (!). I suspect to know what is going on here (the halftone pattern), and this is a more general issue, so I started a new issue (#140).

Closing this issue.
