### ISSUE TITLE
viewflif: window size limited to screen size

### ISSUE THREAD

**Issue by matthiaskrgr** [FLIF-hub/FLIF#145]
When opening an image which is bigger than my physical screensize, viewflif opens with the size of the screen truncating part of the image.

There should be a better way to handle this, maybe let the user scroll around inside the image or make the window bigger than screen size?

**Comment by jonsneyers** [comment]
Hm, here it creates a window that is larger than the screen. Still not convenient of course (you have to move the window around to see the image).

However, I'm reluctant to turn `viewflif` into an actual image viewer, which can do things like zoom and pan etc. There are many image viewers already. `viewflif` is just a demo of the libflif API so that the authors of other image viewers have some example code to look at when adding FLIF support to their program. So I'm saying "wontfix" here, I hope you understand.

**Comment by matthiaskrgr** [comment]
Okay, It might be related to my windowmanager (i3) then...
