### ISSUE TITLE
test-roundtrip.sh fails on image / unexpected file end while decoding

### ISSUE THREAD

**Issue by matthiaskrgr** [FLIF-hub/FLIF#198]
````
cd src
make test # to build all required binarys
wget "https://gitlab.com/freedroid/freedroid-src/raw/master/graphics/blasts/iso_blast_bullet_0008.png"
../tools/test-roundtrip.sh iso_blast_bullet_0008.png tmp.flif tmp.png
````
fails here:
````
+ ./flif -i ../iso_blast_bullet_0008.png tmp.flif
+ ./flif -d tmp.flif tmp.png
Row 29: Unexpected file end. Interpolation from now on.
++ compare -metric AE ../iso_blast_bullet_0008.png tmp.png null:
+ test 1 = 0
````

**Comment by matthiaskrgr** [comment]
From the benchmark repo, /test_images/icons/selection-end-symbolic-rtl.symbolic.png also seems to cause problems.

**Comment by matthiaskrgr** [comment]
In case  of iso_blast_bullet_0008.png , there seems to be one pixel difference
````
 compare iso_blast_bullet_0008.png tmp.png -compose src diff.png 
````
![diff](https://cloud.githubusercontent.com/assets/476013/11623457/580cffcc-9ccd-11e5-9b26-e902a568f506.png)

**Comment by jonsneyers** [comment]
The issue is with the very last byte, which is not flushed.
In the past, this didn't cause incorrect behavior because every file ended with a 4-byte checksum, so in the worst case, the checksum didn't match but the decoded file was still OK.
In one of the previous commits though, I made the checksum optional, and only made the encoder write a checksum if the compressed filesize is larger than 100 bytes. The idea is that a checksum is overkill for tiny files (I'm not sure if that's a correct assumption, but anyway the encoder can add a checksum if it wants to).
I'll make a quick fix, perhaps it is now outputting one byte too much in some cases though...

**Comment by matthiaskrgr** [comment]
There still seem to be problems ( test_images/icons/xfce-wm-unmaximize.png  for example )

````
+ /home/matthias/vcs/github/FLIF/src/flif -i ./xfce-wm-unmaximize.png /tmp/bla.flif
+ /home/matthias/vcs/github/FLIF/src/flif -d /tmp/bla.flif /tmp/bla.png
Row 19: Unexpected file end. Interpolation from now on.
++ compare -metric AE ./xfce-wm-unmaximize.png /tmp/bla.png null:
+ test 7 = 0
````
