### ISSUE TITLE
Lossy FLIF compressor

### ISSUE THREAD

**Issue by kenOfYugen** [FLIF-hub/FLIF#220]
I have experimented in the past with [pngquant](https://github.com/pornel/pngquant), a tool that "converts 24/32-bit RGBA PNGs to 8-bit palette with alpha channel preserved". I was surprised with the resulting file size optimization when targeting a threshold image quality difference. 

Does a similar method to achieve the same compression method exist in FLIF?
If not, would there be potential in implementing such a compressor?

**Comment by jonsneyers** [comment]
You could of course use pngquant on a PNG and then encode that to FLIF. You might want to encode with `-P0` to disable the palette so you still get nice progressive decoding.

But there are better ways to do lossy FLIF, that don't require something as drastic as reducing the number of colors to just 256. For example, you can reduce the number of colors less drastically, e.g. use `convert orig.png -depth 7 lossy.png` to reduce the color space to 21-bit RGB instead of 24-bit. This will not help very much to make the PNG file smaller (since the 7-bit numbers are still stored in bytes), but it will make the FLIF file smaller. E.g. JPEG, because of its lossy YCbCr color transform, is roughly speaking effectively 7-bit in the R and B channels (in the G channel it is almost 8 bit), even at quality setting 100. So reducing the color depth to 7-bit is probably not a huge deal (compared to 8-bit palettes).


Even better would be to do lossy compression by taking into account the actual FLIF algorithm, that is, by modifying pixels such that they get closer to their predicted value, and if they differ a lot, then quantize the difference in such a way that it becomes cheaper to encode (i.e. drop least significant mantissa bits of the delta).
This is trickier to do, but it could result in significantly smaller files with minimal perceptual artifacts.
@hrj has been looking at that, I don't know how far he got though.

**Comment by jonsneyers** [comment]
https://github.com/FLIF-hub/FLIF/commit/00935b856ac8964b911a1d9545929ff3dbc3897c added support for lossy encoding.
