### ISSUE TITLE
CRC optimisations

### ISSUE THREAD

**Issue by est31** [FLIF-hub/FLIF#224]
I have seen that you stated on gitter that CRC takes up 10% of the decoding. I've looked at the code and found some things to optimize for CRC:

* Don't generate the `CRC32KTable` at startup but pass it with the binary. This will probably increase startup time, other libraries do this too for their CRC.
* Do the checksum on the compressed data, not on the decompressed one. That way the amount of bytes to run the checksum over gets reduced by FLIF's compression ratio. There are better ways to assert FLIF is indeed lossless. You can extend this to have every layer of image data be accompanied by one crc32 field so that even partial decoding has a crc sum to compare against.
* Perhaps try whether its faster with a larger initialisation array? Perhaps it helps, because then less computations have to be executed, perhaps it doesn't because stuff is more likely to be in cold memory (most probably the case if the array size is smaller than usual payload data). See this page: http://create.stephan-brumme.com/crc32/

**Comment by jonsneyers** [comment]
Thanks, this is very helpful information!

**Comment by jonsneyers** [comment]
Switching to Slicing-by-16 with prefetch helps a lot to make it faster.

I also changed the CRC computation a bit: it's now simply doing the CRC over the entire buffer for each color channel, instead of doing it pixel by pixel (which meant lots of row/column calculations). The resulting CRC is different though, because I'm now considering the data as it is stored (which typically means 8-bit per subpixel for R/Y, 16-bit per subpixel for G/Co and B/Cg, and 8-bit per subpixel for Alpha), instead of treating every subpixel as a 16-bit value with the least significant byte first. Oops! I suppose that means that I may have introduced a big endian / little endian incompatibility!

The lookup table is bigger (16kb memory + binary size), but in many use cases this is better.
The compile-time option LARGE_BINARY (which was already there to control template explosion) is checked: if a smaller binary is desired, it will generate the table at startup, otherwise it will embed the table in the binary. Actually now that I think about it, it would be better not to generate the table at startup but only if an actual CRC gets computed.

Doing the checksum on the compressed data would be faster since it is less data, but
1) then I can no longer use the checksum as a correctness verification (OK this is not a good reason, I can just as well decompress to a file and use imagemagick to compare it to the original, though that takes quite a bit longer on a large test set)
2) more importantly, it means that either the CRC has to be computed while encoding/decoding is going on, or the encoder/decoder has to do a second pass over the compressed stream (which is problematic if it's not a regular file or memory buffer but e.g. a pipe). The full pixel data is actually available in memory, while the compressed stream is never really in memory (at the moment just one byte at a time).

**Comment by est31** [comment]
Glad to hear the tip helped!

For the correctness verification you can add a new repo with reference test images that get compessed + decompressed as a sort of unit test.

For the CRC computation issue: yes its a valid point. yes it is possible to compute the CRC while rea

**Comment by est31** [comment]
Glad to hear the tip helped!

For the correctness verification you can add a new repo with reference test images that get compessed + decompressed as a sort of unit test.

For the CRC computation issue: yes its a valid point. It is possible to compute the CRC while reading the array, probably with adding the checksum to a buffer that once full gets added to the CRC state using the slice by 16 method. Probably it gets into the way of decoding/encoding though, as the CRC lookup table now uses the cache during the whole time... But this is all speculation ofc :) no ideas what would be fastest.

**Comment by jonsneyers** [comment]
Buffering the compressed I/O could be a good idea (for performance) regardless of the CRC.

If the CRC gets computed on the fly, it should be the 1-byte at a time method, to avoid cache pollution with that 16KB lookup table. Even then there's a 1KB lookup table that will probably stay in cache, which will have a negative effect on performance. And if you want a compressed-stream CRC, you can just as well use external tools to compute and verify the CRC separately.

If the goal is just to detect file corruption, we could also just make a CRC based on the bottom row (or couple of rows) of the image -- there's no way to get those pixels right without getting the other pixels right as well, so as a corruption check it would be just as effective.

I think the current situation is OK: by default, the encoder adds a CRC and the command line decoder checks it, but it's optional in both of them, and the decode library doesn't check the CRC by default. And the CRC computation is pretty fast now.

**Comment by est31** [comment]
Fine, glad I could help
