### ISSUE TITLE
Compression ratio regression @ fed3ea1

### ISSUE THREAD

**Issue by c0nk** [FLIF-hub/FLIF#230]
source image:
![sample](https://cloud.githubusercontent.com/assets/10184038/13564492/6ba505ec-e44a-11e5-8291-3d32436e391e.png)

output sizes:
146916 sample.d9301fe.flif
147679 sample.fed3ea1.flif

**Comment by jonsneyers** [comment]
When I say "compression improved", I don't mean that for every single image the file becomes smaller. Some files may become bigger, others may become smaller. As long as on average, the compressed images become smaller, I call it an improvement.

Lossless compression is essentially enumerating all possible inputs in such a way that you put images you're more likely to encounter (but what does that mean?) earlier in the sequence. Those images will get a more concise representation, while other images (e.g. pure noise) get a less concise representation. There is no way around that: you'll win on some (hopefully most), but you'll lose on others.

**Comment by c0nk** [comment]
The imagine in question is not "noise" but is a 16bit DEM. FLIF seems very well suited for this use case and it should be a priority IMO. The commit in question doesn't claim to "improve" compression. It is titled "changed some defaults to make encoding a bit faster...".  Would it make sense to be able to set these parameters on the command line if it helps some classes of images?

**Comment by jonsneyers** [comment]
Ah sorry I assumed you were talking about the more recent commits, I didn't check the commit number.

To use the old defaults, use `flif -R3 -T40`. You can also take a look at https://github.com/FLIF-hub/flifcrush if you are interested in finding optimal parameters -- full flifcrushing will take a long time, but maybe if you have several images of the same "type", you can crush a few of them and see if you get encode parameters out of it that work better than the defaults.

The new default (since that commit) is to do only 2 learning iterations instead of 3, which obviously makes encoding faster, but also somewhat worse. Most of the gain you get by going from 0 to 1, and then going from 1 to 2 still usually gives a good improvement. Going to 3 or 4 is almost always slightly better than 2, but the difference was considered small enough to ignore, at least for a default setting.

**Comment by jonsneyers** [comment]
Closing the issue now, I think it is resolved.

**Comment by c0nk** [comment]
Thanks for the explanation.
