### ISSUE TITLE
malformed input file causes hang and high load

### ISSUE THREAD

**Issue by hannob** [FLIF-hub/FLIF#231]
The attached file causes the flif decoder to hang and the CPU load and memory use will be extremely high.

(as github doesn't allow the upload of flif files I zip-ed it)
[flif-hang.zip](https://github.com/FLIF-hub/FLIF/files/161337/flif-hang.zip)

**Comment by jonsneyers** [comment]
This is what I get on that image:
```
Decoding 65530x65530 image, channels: 3, depth: 8 bit
Error: could not allocate enough memory for image data.
Error: could not decode FLIF file
```
I could add a check in the decoder so that it refuses to even try to allocate a buffer large enough for such a huge image (e.g. you would compile it with a megapixel limit), but other than that, I think this is normal behavior.

If on your system, CPU and memory use go up, it's probably because your OS is not just refusing to allocate that much memory (I estimate that FLIF will be asking for about 20 GB), but it is moving stuff to swap and probably grinding everything to a halt while doing that.
