### ISSUE TITLE
Feature request: Ability to decode all channels upto target resolution.

### ISSUE THREAD

**Issue by hrj** [FLIF-hub/FLIF#276]
As an end-user, who may not understand the internals of FLIF format, I expect to see the thumbnail preview of an image at its best quality. Currently, the `-rWxH` option decodes the input stream until the first channel meets the target resolution and then stops decoding.

I think there should be an option to continue decoding until all channels reach the target resolution. Otherwise, for some images, the resulting image looks weird. Paletted animations seem to suffer the most.

**Comment by hrj** [comment]
I realize that this option would have a trade off, it would require more time and memory to decode all channels to target resolution.

**Comment by jonsneyers** [comment]
The animated palette problem was actually an encoding issue, caused by the FrameLookback being encoded too early, which leads to a suboptimal progressive decode ordering. While it could be fixed without breaking the bitstream (by using a non-default ordering), I fixed it by changing the default ordering to be better in this case.

As for the feature request: I added `-fWxH`, which produces an exact WxH downsampled image. It will internally use buffers that are possibly larger than WxH, and then downsample from that. So this is what you probably want to do in a browser, if you know the desired target dimensions and you are fine with aliasing artifacts (to avoid aliasing, you still need to decode more pixels and manually downscale from there; in extreme cases like a checkerboard with 1 pixel squares, you even need to decode everything to get an accurate downscaled image).
You can also drop `W` or `H` (or make it zero) and then it will pick something that satisfies the aspect ratio of the image. If you set `W` and `H` to incorrect-aspect-ratio values, then you'll get an incorrect-aspect-ratio output, so you probably don't want to do that.
