### ISSUE TITLE
Reproducible FLIF encoder crash on specific input

### ISSUE THREAD

**Issue by Ipquarx** [FLIF-hub/FLIF#285]
Using the FLIF Native Executable found here: http://flif.info/software.html
Trying to encode the following image: http://i.imgur.com/VBhlhZo.png
With the following parameters: `flif -v -n FILENAME.png out.flif`

Causes the encoder to crash before actually encoding the file.

Picture of the crash (Tried several times to make sure it was the same every time):
![](http://i.imgur.com/6XEl3cx.png)

Text in "problem details":
```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	flif.exe
  Application Version:	0.0.0.0
  Application Timestamp:	561fbee1
  Fault Module Name:	StackHash_b4d1
  Fault Module Version:	6.1.7601.23418
  Fault Module Timestamp:	5708a73e
  Exception Code:	c0000374
  Exception Offset:	000ce843
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	4105
  Additional Information 1:	b4d1
  Additional Information 2:	b4d18d2a8db90f48918c746580f2872f
  Additional Information 3:	a525
  Additional Information 4:	a5250598940a522f3fd3aaf2a229d185
```

**Comment by jonsneyers** [comment]
This is a very old version of FLIF, from almost a year ago.
I don't know what this bug was, but whatever it was, it seems to be fixed. The current version of FLIF encodes that file without any problems.

Thanks anyway for the bugreport. We should probably update the website with a more recent build.
