### ISSUE TITLE
Specify lossy quality using a target DSSIM?

### ISSUE THREAD

**Issue by hrj** [FLIF-hub/FLIF#320]
Using the current quality setting for lossy encoding seems to be a bit of a trial-and-error process. If I want to encode a set of images with a certain level of quality, how do I determine what setting to use? Would it make sense to specify quality as follows: "target a DSSIM of 0.01".

The encoder could then do the following:
* Pick an initial lossiness level that matches the target DSSIM.
* Perform a simple hill-climbing algorithm. Adjust lossiness till the target DSSIM is reached.

**Comment by jonsneyers** [comment]
I think this is best left to an external tool. Including it in the encoder itself adds bloat to the code (since you would need to include a DSSIM metric). Perhaps even all of the lossy preprocessor code should be removed from the main tool and turned into a standalone tool (like e.g. pngquant). The only reasons why I did include that in the main tool is 1) convenience, and 2) the intricate link between how the encoding works and how the lossification works.

On the other hand, including this in the encoder itself would be more efficient, because it can do the DSSIM search before doing any actual encoding.

Perhaps a good compromise solution would be to support something like
`flif -Q50 input.ppm lossified.ppm`
i.e. just run the lossy preprocessor and instead of saving the result as a FLIF file, save it as uncompressed pixels. That way, an external tool can efficiently try different amounts of loss, without having to encode and decode a FLIF file every time.

**Comment by hrj** [comment]
> including this in the encoder itself would be more efficient, because it can do the DSSIM search before doing any actual encoding.

Yeah, from an efficiency and convenience point of view, it would be nice to have this option in the same binary. The lossy preprocessing code would stay in sync with the FLIF encoder.

However, if you think it is too much bloat, please close the issue.

**Comment by jonsneyers** [comment]
Well, a good DSSIM metric needs to convert to Lab color space, which means floating point arithmetic and storage (something we currently don't need), and then do some stuff with that, which is easy to do if you don't care about a dependency to OpenCV or something like that, but not so trivial otherwise.
Also, we can't just use Kornel's DSSIM code, because it is AGPL-licensed which would make the encoder license much stricter. So we would have to roll our own. It's easy to make a DSSIM metric using OpenCV, but that's a big dependency, which I want to avoid.
So all in all, I think it's a lot of effort for little gain.

But the compromise solution I proposed above should be easy to do, and it would be enough to make an external tool nearly as efficient as an internalized solution.

Also, DSSIM is just one metric, there are others....

**Comment by hrj** [comment]
Good points. I will raise a separate issue for the compromise solution and close this one.
