### ISSUE TITLE
Progressive decoding causes significantly slower performance

### ISSUE THREAD

**Issue by SaschaNaz** [FLIF-hub/FLIF#333]
In [libflif.js demo page](https://saschanaz.github.io/libflif.js/): Progressive way of decoding Lenna.flif takes 2153 ms, while non-progressive way (first callback quality = 10000) takes 696 ms.

JavaScript overhead seems not to be key cause of this issue as it showed negligible sub-50ms delay per callback (7 callbacks). Testbed is Chrome 55.0.2883.87 64bit and Core i5-2400. (Same on Firefox and Edge)

**Comment by lehitoskin** [comment]
Seems like #89 is related. I don't know if this means the actual `flif_decoder_decode_file/memory` or `flif_image_read_row_rgba8/16` or both!

**Comment by jonsneyers** [comment]
Every intermediate rendering forces making a copy of the buffer, interpolating what has not yet been decoded, and doing all color transforms in reverse (e.g. YCoCg). So if you have 7 callbacks, you're doing some of the decoding 7 times, and in addition quite a bit of interpolation (and that interpolation code is not yet optimized).

So the time difference is not surprising. Some of that is inherent, probably a lot of it can be reduced by optimizing things better. In any case, doing fewer callbacks (setting larger quality jumps) will help. E.g. a three-step progressive decoding with first callback quality 500 (5%), next callback quality 5000 (50%) and last callback quality 10000.

**Comment by SaschaNaz** [comment]
>E.g. a three-step progressive decoding with first callback quality 500 (5%), next callback quality 5000 (50%) and last callback quality 10000.

This in fact decreases the delay to 1250 ms but it still is way longer than non-progressive 700 ms.

**Comment by benepo** [comment]
bounty incentive: https://freedomsponsors.org/issue/804/progressive-decoding-causes-significantly-slower-performance

**Comment by SaschaNaz** [comment]
>Every intermediate rendering forces making a copy of the buffer, interpolating what has not yet been decoded

Can we provide an option to skip the interpolation and leave web browsers do it?

**Comment by hrj** [comment]
I did a quick benchmark and analysis. The [relevant part of the code](https://github.com/FLIF-hub/FLIF/blob/master/src/flif-dec.cpp#L714-L725) does a couple of things before the callback is invoked:
1. Make a copy of the images
2. Make a copy of the transforms and zoom levels
3. Interpolation of pixels
4. Image.normalize_scale()
5. transforms.undo_redo_during_decode() and transforms.invData()

Of these, the interpolation of pixels (3) doesn't incur any overhead in my benchmark. The biggest performance impact is from (5) and (1) in that order.

**Comment by hrj** [comment]
BTW, my benchmark image had these transforms: `Channel_Compact[13,119,63], YCoCg, Bounds, Palette`, which explains the high transform overhead.

**Comment by hrj** [comment]
My thoughts:

Even if we optimise the path around the progress-callback, the actual impact on user experience also depends on:
* the speed of the processing platform (CPU speed, JS v/s native, etc)
* the speed of the IO channel
* the size of the image

Hence, a general solution to this problem could be to *lazify* this critical-path. That is, instead of eagerly doing those 5 steps and then invoking the callback function, just pass a class containing the information as a parameter to the call back. The call back can use its own heuristics to decide whether it needs the in-progress frames, with or without interpolation.

For example, if the callback sees that 400ms have elapsed since last progress update, it might request the in-progress frames and render them. But if it sees that the current progress update is only 50ms since the last update, it might ignore the update, thus saving the overheads.

Thoughts?

**Comment by SaschaNaz** [comment]
Yes, I think that's what browsers do now. :+1:

**Comment by hrj** [comment]
@jonsneyers Apart from the lazification, one more idea:

When preparing the partial_images, instead of doing interpolation and then transforms, would it make sense to do the transforms first and then interpolate? The transforms would be faster on the smaller image, and since transforms are costly it should help improve performance. The overhead of interpolation should remain the same.

If it sounds feasible, I can attempt a PR.

**Comment by hrj** [comment]
After the PR merge and fix for #381 and changes to viewflif in #384, I was able to run benchmarks for some larger images. I will run the same benchmarks in JS later.

### Image info

| File               | Resolution | Interlaced | Transforms                                         |  BPP   |
| -------------      | ---------- | ---------- |  ---------------------------                       | ---    |
| [street.flif][1]   | 1800x1200  | Y          | YCoCg, Bounds, Color_Buckets                       | 8.37   |
| [street-N.flif][2] | 1800x1200  | N          | YCoCg, Bounds, Color_Buckets                       | 8.15   |
| [2k-2k.flif][3]    | 2000x2000  | Y          | Channel_Compact[13,121,63], YCoCg, Bounds, Palette | 0.0036 |


### Benchmark
| File          |  Preview steps before  | Preview steps after | Time Before   | Time After  |
| ------------- | ---------------------  | ----------------    | ----------    | ----------  |
| street.flif   |  7                     | 3                   | 1.86s         | 1.36s       |
| street-N.flif |  3                     | 2                   | 1.26s         | 1.17s       |
| 2k-2k.flif    |  4                     | 2                   | 0.35s         | 0.23s       |


  [1]: https://hrj.github.io/static/flifs/street.flif
  [2]: https://hrj.github.io/static/flifs/street-N.flif
  [3]: https://hrj.github.io/static/flifs/2k-2k.flif

**Comment by SaschaNaz** [comment]
Great, will take a look soon :D

**Comment by hrj** [comment]
Benchmark with PolyFlif, after adding the time >0.6second condition in callback. Note that PolyFlif requests different quality levels than viewflif, hence has different number of render steps.

### Benchmark with polyflif, preview threshold = 0.6s
| File          |  Render steps before   | Render steps after | Time Before   | Time After  |
| ------------- | ---------------------  | ----------------    | ----------    | ----------  |
| street.flif   |  6                     | 5                   | 12.253s       | 9.327s      |
| street-N.flif |  3                     | 3                   | 6.712s        | 6.7s        |
| 2k-2k.flif    |  7                     | 3                   | 20.894s       | 9.959s      |

**Comment by SaschaNaz** [comment]
>hence has different number of render steps.

I just implemented my own steps, now every implementation have their own one.

**Comment by hrj** [comment]
> I just implemented my own steps, now every implementation have their own one.

Nice :smile: 

Btw, I am now trying out the idea of running the transforms before the image interpolation.

**Comment by hrj** [comment]
I re-ran the benchmarks for the steps involved in preparing the preview image, with better accuracy. Results:
![lenna](https://cloud.githubusercontent.com/assets/345879/25004467/2bd02798-2072-11e7-949d-6d29aa12c892.png)
![street](https://cloud.githubusercontent.com/assets/345879/25004471/2fffb072-2072-11e7-9520-6b44b0477df4.png)
![2k-2k](https://cloud.githubusercontent.com/assets/345879/25004473/33a3218c-2072-11e7-9bd0-17b7f2064368.png)


### Analysis
Sorry, my initial analysis was a bit wrong. Interpolation does consume significant time, especially during the first few callbacks (when it has to interpolate more). Transforms take the same amount of time for all callbacks, and I still think it is worth doing them before the interpolation. I am still working on it; doesn't look easy. 

Cloning is another significant part which could be optimised.

**Comment by benepo** [comment]
Nice progress @hrj and @SaschaNaz !  I'd be curious to see the optimization effect compared to both polyfills: https://github.com/SaschaNaz/libflif.js/issues/9 and https://github.com/UprootLabs/poly-flif/issues/13

**Comment by hrj** [comment]
I was not able to optimise "transformations" by changing their order :( Will look at it later, along with other ideas.

I did optimise "cloning" and "interpolation": https://github.com/FLIF-hub/FLIF/pull/394

Time consumed in previews with PolyFLIF:

| File | Before #394 | After #394 |
| ---- | ---- | ---- |
| Lenna.flif | 1.118s | 0.871s | 
| Street.flif | 6.66s | 4.279s |
| 2k-2k.flif | 15.408s | 12.8s |

**Comment by hrj** [comment]
@jonsneyers I figured out how to do transformations before interpolation. We need to interpolate all planes to a common zoom level first. Then do the transformation at the common zoom level, then interpolate to zoom level 0.

This works for all images, except [clock.flif](https://uprootlabs.github.io/poly-flif/assets/clock.flif). It is an animation with transparency, with the following transforms: `Channel_Compact[141,69,70,17], YCoCg, Bounds, Palette_Alpha, Frame_Shape, Frame_Lookback`

At the time of first call back with quality = 12.66, each plane has the following zoom levels: 3, 2, 3, 2, 2

Firstly, why does plane[0] at a higher zoom level than plane[1]? Isn't it usually true that first plane is decoded ahead of following planes? Secondly, even if we interpolate all planes to zoomlevel = 2, then transform + interpolate, the resulting image looks only partially interpolated.

Should I avoid this technique for certain types of images. It seems to work fine for majority of images.

**Comment by jonsneyers** [comment]
Reopening since it is in fact still an active issue.

Palette_Alpha takes planes 0,1,2,3 and puts the palette indexes in plane 1, setting planes 0,2,3 to constant planes containing all zeroes. Constant planes are completely skipped (which is a performance optimization; their encoding would never produce any output bits in the stream), and their zoomlevel doesn't matter since everything is known already.

Interpolating planes before undoing transformations is not always safe. Frame_Lookback adds a fifth plane (plane 4) which contains references to earlier frames. Interpolating that is not a good thing to do. Interpolating palette indexes is also not a good thing to do. And interpolating the alpha channel is probably also a bit risky, because you could be making fully transparent pixels visible.

**Comment by hrj** [comment]
Got it, thanks! So for now, I am thinking of detecting if there are complex transforms such as `Palette-*` and `Frame-*` and not do the transform-before-interpolation optimisation in those cases.

Aside, some questions:
* Why does Palette_Alpha use plane 1, and not plane 0?
* "interpolating the alpha channel is probably also a bit risky, because you could be making fully transparent pixels visible". Is that addressed in the current algorithm? I couldn't find a special case for alpha channel.
*  The `clock.flif` has both the `YCoCg` transform and the `Palette` transform. Could the `YCoCg` be avoided if `Palette` is already present?

**Comment by hrj** [comment]
After the optimisations to transformations and https://github.com/FLIF-hub/FLIF/pull/407:

Ratio of decode time to previous decode time:
* Lenna.flif : 73%
* street.flif : 79%
* 2k-2k.flif : 78%

![lenna](https://cloud.githubusercontent.com/assets/345879/25452265/a841334c-2ae2-11e7-87c7-ed3a990fa76e.png)

![street](https://cloud.githubusercontent.com/assets/345879/25452273/ac8dc5c8-2ae2-11e7-85d2-053a7b9b2e8f.png)

![2k-2k](https://cloud.githubusercontent.com/assets/345879/25452276/b0d03b52-2ae2-11e7-8e14-13cebea58856.png)


### Overall Summary
Since I began working on this issue, the time for first preview is about 50% of what it was earlier. In addition, the number of previews can now be reduced by the viewer based on its heuristics.
