### ISSUE TITLE
Resized or refitted quality is very poor

### ISSUE THREAD

**Issue by hrj** [FLIF-hub/FLIF#344]
For [this input FLIF file](https://uprootlabs.github.io/poly-flif/assets/1_webp_ll.flif), the fully decoded image is nice:

![1webp](https://cloud.githubusercontent.com/assets/345879/21837323/4306af64-d7f1-11e6-85f6-aafb31118d42.png)

However, with `--resize=200x151` we get this:
![1webp-r](https://cloud.githubusercontent.com/assets/345879/21837333/5b311b42-d7f1-11e6-90ed-5be270c5a7df.png)

and similarly with `--fit=200x151` we get:
![1webp-f](https://cloud.githubusercontent.com/assets/345879/21837341/6ab71c74-d7f1-11e6-9055-5422ff631ddb.png)

It looks like chroma zoom levels are not being decoded to the same level as luma. Am I right?

**Comment by hrj** [comment]
Output of `flif -vvvv --resize=200x151 assets/1_webp_ll.flif 1webp-r.png`

```
  ____ _(_)____
 (___ | | | ___)   FLIF (Free Lossless Image Format) 0.3 [4 Jan 2017]
  (__ | |_| __)    Copyright (C) 2016 Jon Sneyers and Pieter Wuille
    (_|___|_)      License LGPLv3+: GNU LGPL version 3 or later

This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Input file is a FLIF file, adding implicit -d
Decoding 400x301 image, channels: 4, depth: 8 bit
Decoding downscaled image at scale 1:2 (400x301 -> 200x151)
Transforms: Channel_Compact[227,215,226,255], YCoCg, Bounds[0:12..218][1:-71..212][2:-98..77][3:0..255]
Invisible pixel predictor: -H2
Decoded header + rough data. Decoding MANIAC tree.
Decoding data (interlaced)
6% done [0/23] DEC[3,100x38]      read 2623 bytes   
7% done [1/23] DEC[0,100x38]      read 3192 bytes   
9% done [2/23] DEC[3,100x76]      read 3356 bytes   
12% done [3/23] DEC[0,100x76]      read 4519 bytes   
15% done [4/23] DEC[3,200x76]      read 4749 bytes   
22% done [5/23] DEC[1,100x38]      read 5376 bytes   
23% done [6/23] DEC[0,200x76]      read 7339 bytes   
29% done [7/23] DEC[3,200x151]      read 7756 bytes   
42% done [8/23] DEC[1,100x76]      read 8950 bytes   
45% done [9/23] DEC[0,200x151]      read 12959 bytes   
58% done [10/23] DEC[3,400x151]      read 14244 bytes   
83% done [11/23] DEC[2,100x38]      read 14669 bytes   
84% done [12/23] DEC[1,200x76]      read 16543 bytes   
91% done [13/23] DEC[0,400x151]      read 17721 bytes   
139800 subpixels done, 120400 subpixels todo, quality target 100% reached (116%)
INTERPOLATE[0,400x301]                 
INTERPOLATE[1,200x151]                 
INTERPOLATE[1,400x151]                 
INTERPOLATE[1,400x301]                 
INTERPOLATE[2,100x76]                 
INTERPOLATE[2,200x76]                 
INTERPOLATE[2,200x151]                 
INTERPOLATE[2,400x151]                 
INTERPOLATE[2,400x301]                 
INTERPOLATE[3,400x301]                 

Decoded input file assets/1_webp_ll.flif, 17721 bytes for 200x150 pixels (4.7099bpp)   
Not checking checksum, lossy partial decoding was chosen.
Saving output file: 1webp-r.png  
```

**Comment by hrj** [comment]
Ah, I remember discussing these problems before. At the risk of repeating myself, there are two solutions:

* The quality of interpolation ought to be improved. The pixel predictor doesn't work well when applied repeatedly for interpolation.
* Alternatively, there should be some way to indicate "decode all channels to specified size". While an application could do this by decoding to a larger size and then downscaling, it is inconvenient and confusing for a user to do it on the command line. The current behavior appears like a bug, because user sees a lossless format behaving extremely weirdly when asked to resize. It would be nice if the decoder itself could do the "decode to higher res followed by downscaling to specified size".

**Comment by hrj** [comment]
Update: Fixed the link to the FLIF file in the first comment.

**Comment by jonsneyers** [comment]
This was caused by the same bug as #345, just it didn't segfault in this case but corrupt the buffer. Should be better now.

**Comment by jonsneyers** [comment]
Please verify that it's better now, and close the issue if it's OK.
And you're right that it is effectively doing chroma subsampling when decoding at lower scale (at least with the default zoomlevel order; it would be possible to have an encode option that uses a non-chroma-subsampling zoomlevel ordering). If you want to make sure that all pixels have exact chroma, you have to decode at twice the target resolution. That's a good idea anyway, because it will give you twice the luma you need, so downscaling manually from that will give you less aliasing artifacts caused by the sampling nature of FLIF. (Note that --fit will not help for that, because it uses stupid sampling to do the fitting. You need to do --resize and then some real downscaling from that.)

**Comment by hrj** [comment]
Yup, it decodes fine now. Closing this.

> If you want to make sure that all pixels have exact chroma, you have to decode at twice the target resolution.

Will this not be difficult for CLI users? Or is the implementation here not meant for general use -- only as a reference?

**Comment by jonsneyers** [comment]
My assumption is that for most users, it is fine to do chroma subsampling by default when decoding at lower quality / smaller size. After all, most JPEG tools also do 4:2:0 by default, and lossy WebP doesn't even support 4:4:4.

**Comment by hrj** [comment]
> My assumption is that for most users, it is fine to do chroma subsampling by default when decoding at lower quality / smaller size.

Yeah, I kind of agree. The only hitch is that because it is a "lossless" format and because it is the new kid on the block, it has the advantage / choice to do better than the incumbents.

Aside, from your comment on the polyFLIF issue:

> So you're still better off using --resize to twice the target dimensions, ...

Why do you feel polyFLIF needs to be different than the CLI tool? Just trying to understand your reasoning better.

**Comment by jonsneyers** [comment]
The CLI tool does one thing (in the Unix philosophy). It encodes/decodes FLIF files. That's it. It can partially decode images in various ways, but it's up to the user to do anything with the resulting output image. And the partial decodes it produces are ultimately always power-of-two downsampled images from the original, with lower resolution on chroma than on luma; what is not decoded is interpolated but the underlying dimensions are always downsampled by a power of two.

PolyFLIF does more than one thing. It decodes FLIF files, but it also renders them to the screen (and in the case of animations, it animates the frames). So it knows the intention of the user: viewing the image, in the dimensions of the target canvas, in good quality while avoiding to decode the whole thing. The only way to do that for arbitrary image vs canvas dimensions, is to decode a bit more than necessary and downscaling from there (unless you're lucky and the canvas dimensions happen to be an exact power-of-two divisor of the image dimensions). How much more, depends on how much quality you want: if you want to avoid aliasing artifacts completely, you have to decode the whole thing and downscale it properly. If you use two times the canvas dimensions, then you are guaranteed to have enough luma pixels, so that's probably good enough in practice. If you use four times the canvas dimensions, then you certainly have enough to have exact luma and chroma pixels, but there might still be aliasing artifacts if the original is way bigger than that. It's a trade-off between quality and how much of the file you want to download/decode. There's no "correct" choice here. But to me, using between 1 and 2 times the canvas dimensions for the decode (so `--resize [2 times canvas dimensions]`) seems a reasonable trade-off in most cases. Using less than that would mean you might not have enough pixels in the decode and a browser-side upscale would be needed, which is bad. Using more than that is going to result in better image quality but at a significant cost in memory, cpu and bandwidth.

My point is: the CLI tool is not in a position to make such trade-offs. PolyFLIF is in a somewhat better position since it is a more or less specific use case (though it still does not know everything). And since browsers already have reasonable built-in downscaling algorithms (probably bicubic or something), it's probably fine to just let the browser do the final downscale.

**Comment by hrj** [comment]
@jonsneyers I see your view point better now. Although I don't fully agree with it, I am now convinced that I need to do this in PolyFLIF.

To elaborate my reasoning, somebody in this pipeline needs to take care of resizing quality:
```
WebApp | PolyFLIF | libFLIF
```

Since PolyFLIF intends to be a drop-in supplement to the browser's image support, asking the  WebApp to take care of scaling issues doesn't make sense. That leaves PolyFLIF and libFLIF as the candidates.

My thought was that, putting the logic in libFLIF would avoid redundancy across the library clients. Apart from PolyFLIF and the CLI tool, I suppose every image viewer would now have to handle this properly.

Since you are not keen on doing this in libFLIF (and I understand and respect your reasons), I will implement this in PolyFLIF. Fortunately, most browsers do support good downscaling, so I can bank on that.

**Comment by jonsneyers** [comment]
Just to elaborate on why I don't want to do this in libflif:
Downscaling is actually harder than it seems. To do it really right, you should work with Linear RGB (not sRGB which is non-linear), and there are a LOT of downscaling algorithms out there, that each have a different behavior in terms of the trade-offs they make between the different artifacts you can get. See for example http://www.imagemagick.org/Usage/filter/nicolas/ for a good discussion of this.

Now in practice you can usually get away with something simple (e.g. some cubic filter on plain sRGB values), which is what most image viewers and browsers probably do. But I don't want to hardcode one specific downscaling filter in libflif – it would add unnecessary complexity to the code, and the choice would be arbitrary. There would also be confusion as to whether that particular downscale method is part of the FLIF format specification or not.

Image viewers, browsers, image editors and basically any application that might want to use libflif probably already has support for some kind of downscaling, so I think it's safe to not duplicate that functionality in libflif itself.

The same is true by the way for color profiles. Libflif just gives you the raw pixel values, which are to be interpreted as sRGB unless there is an ICC color profile in the metadata. There is no code in libflif to do the color conversion (which is needed to properly render a non-sRGB image on an sRGB display, or to render any image on a non-sRGB display). This is also intentional: color management is out of the scope of libflif. (and so is alpha blending and whatever else you might need to do with the image besides decoding the raw pixel values).
