### ISSUE TITLE
`breakpoints` not clear 

### ISSUE THREAD

**Issue by hrj** [FLIF-hub/FLIF#346]
With the [clock.flif](https://uprootlabs.github.io/poly-flif/assets/clock.flif) file:

```
> flif -b clock.flif
Image data starts at offset 12
1:8 scale: 5091 bytes
1:8 scale: 6654 bytes
1:4 scale: 6827 bytes
1:2 scale: 10860 bytes
```

I wonder what the two different lines emitted for `1:8` signify. Or is it a bug?

Doesn't seem to happen for still images.

**Comment by hrj** [comment]
Also, when truncating the file, are we supposed to add the `image data offset` to the `bytes` for a given scale? From a quick glance at the results, it looks we have to add the offset.

**Comment by hrj** [comment]
Also, for the printed number of bytes, do we get all channels at that scale? Or only the luma?

**Comment by jonsneyers** [comment]
You don't have to add the offset, the `bytes` reported are the total sizes of the truncated files that will decode fine with the option `-s SCALE`.
The offset is reported because if we are going to implement the `tRko` chunk (https://github.com/FLIF-hub/FLIF/blob/master/doc/metadata#L36), then we'll have to subtract those offsets, to make sure that adding or removing metadata has no influence on the contents of the `tRko` chunk.

Like with `-s`, you only get full luma (and alpha) at that scale, the chroma channels are subsampled. Or in general (with non-default zoomlevel orderings), what you get is whatever can be decoded with a buffer with the scaled dimensions. With the default zoomlevel ordering, you have to decode the 1:4 luma before you can decode the 1:8 chroma (and you need a 1:4 buffer to decode that luma), so if you only have a 1:8 buffer, the scaled decode will contain 1:8 luma and only 1:16 chroma. (For palette images it is different since those don't have separate luma and chroma, so for this particular animation you actually get all channels at that scale).

The two different lines for 1:8 is a bug, should be fixed now. It only applies to images (or animations) that are small enough, so the 1:8 scale image is actually available in the bitstream before the MANIAC trees are even encoded. The first reported truncation size is the correct one. Should be fixed now.

**Comment by hrj** [comment]
Awesome. Thanks for the fixes and explanation!
