### ISSUE TITLE
segfault in viewflif when input file is truncated

### ISSUE THREAD

**Issue by hrj** [FLIF-hub/FLIF#348]
Input: https://uprootlabs.github.io/poly-flif/assets/clock.flif

truncate with `dd if=clock.flif of=clock-10860.flif bs=1 count=10860`

```
> viewflif clock-10860.flif 

Decoding progressively...
8205 bytes read, rendering at quality=12.66%
10860 bytes read, rendering at quality=25.00%
Row 19: Unexpected file end. Interpolation from now on.
[1]    31183 segmentation fault  viewflif clock-10860.flif
```

**Comment by jonsneyers** [comment]
Thanks for the bugreport! This was caused by the new `-k` option (which is default in libflif), which uses an 8-bit buffer for palette images if possible. However, when the file is truncated, it should convert the 8-bit buffer to 16-bit because it is doing the interpolation that is needed in that case in YCoCg space. It was not doing that convert, causing a segfault. Should be fixed now.
