### ISSUE TITLE
Firefox Browser support

### ISSUE THREAD

**Issue by szepeviktor** [FLIF-hub/FLIF#420]
Hello!

Has anyone opened a Firefox and Chrome issue to natively support FLIF in modern browsers?

**Comment by shaggytwodope** [comment]
@szepeviktor While I don't have the links directly, I know it's been mentioned to chrome(ium). And wouldnt be surprised firefox either. For now we just have the JS means.

**Comment by lehitoskin** [comment]
#350 for Chromium. I don't know if there has been one for Firefox.

**Comment by szepeviktor** [comment]
Thank you.

**Comment by thebombzen** [comment]
Here's one for firefox. [https://bugzilla.mozilla.org/show_bug.cgi?id=1240692](https://bugzilla.mozilla.org/show_bug.cgi?id=1240692)
Also see this for Chromium: [https://bugs.chromium.org/p/chromium/issues/detail?id=539120](https://bugs.chromium.org/p/chromium/issues/detail?id=539120)

Source: [http://flif.info/software.html](http://flif.info/software.html)

**Comment by szepeviktor** [comment]
Thank you.

**Comment by ziemek99** [comment]
FLIF has been superseded by JPEG XL. Due to this fact Firefox bug was closed as WONTFIX and effort has been moved to the [JPEG XL tracking bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1539075).

You can read more about JPEG XL on an [official website](https://jpeg.org/jpegxl/), [community website](https://jpegxl.info) or dig into [GitHub repository](https://github.com/libjxl/libjxl).
