### ISSUE TITLE
Tracker for Webkit FLIF discussion

### ISSUE THREAD

**Issue by gingerbeardman** [FLIF-hub/FLIF#512]
https://bugs.webkit.org/show_bug.cgi?id=186389

**Comment by ziemek99** [comment]
FLIF has been superseded by JPEG XL. Due to this fact WebKit bug was closed as RESOLVED INVALID and effort was moved to the [JPEG XL tracking bug](https://bugs.webkit.org/show_bug.cgi?id=208235), which is marked as... RESOLVED FIXED 😃

You can read more about JPEG XL on an [official website](https://jpeg.org/jpegxl/), [community website](https://jpegxl.info/) or dig into [GitHub repository](https://github.com/libjxl/libjxl).
