### ISSUE TITLE
Finalize the decode stream

### ISSUE THREAD

**Issue by jonsneyers** [FLIF-hub/FLIF#85]
(Leaving room for future enhancements)

**Comment by jonsneyers** [comment]
After some discussion, I think it is clear that it would be premature to actually finalize the format.
The best approach seems to be to temporarily freeze the format (we could call it "FLIF15") so it can actually be used in practice, while continuing research and investigate bitstream-breaking improvements which could lead to a finalized format in two years or so (which we could call e.g. "FLIF17").

**Comment by jonsneyers** [comment]
OK, so it will be FLIF16.

Does anyone have suggestions/considerations w.r.t. finalizing the bitstream?

**Comment by Corillian** [comment]
As someone who is actively watching the development of FLIF with an eye towards evaluating its usefulness for game development my opinion would be that as long as the bitstream is versioned and the decoder can handle legacy streams I see no reason why you shouldn't release sooner rather than later. Two years is a _long_ time and if the file format and decoder are properly designed the quality of encoding/decoding should be able to gracefully evolve over time in a way that makes upgrading as painless as possible.

**Comment by jonsneyers** [comment]
FLIF16 is finalized with the release of v0.2

Future bitstream-breaking changes will go in a different, experimental branch.
Releasing all the experimental stuff while having a decoder that can decode all intermediate versions is probably going to result in a bloated decoder, so it's probably better to keep the experimental stuff separate. Once some new components/ideas/transformations are sufficiently mature, we can consider releasing it as a FLIF17 / FLIF18 bitstream which can then gracefully evolve over time, while making sure the decoder does not have to deal with too much legacy stuff that will end up not being useful.
